// ============================================================
// BOOKING LINKS — Court booking platform URL lookup table
// ============================================================
// Auto-generated by scripts/generate-booking-links.js
// Generated: 2026-07-30
// ============================================================

const BOOKING_BY_ID = {
  "0-0-2-pickle-courts": {
    courtogo: 'https://www.courtogo.com/venues/stayfit-pickle-courts',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "0-0-2-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "aeon-pickle-yard": {
    courtogo: 'https://www.courtogo.com/venues/pickle-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "alferez-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "andot-pickle-court": {
    courtogo: 'https://www.courtogo.com/venues/jims-pickle-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "around-the-post": {
    courtogo: 'https://www.courtogo.com/venues/around-the-post',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "balamban-homecourt-yard": {
    courtogo: 'https://www.courtogo.com/venues/homecourt-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "big-j-paddle-grounds-apokon": {
    courtogo: 'https://www.courtogo.com/venues/paddle-ground',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "btc-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "budz-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "carcar-city-the-pickle-pub": {
    courtogo: 'https://www.courtogo.com/venues/the-courtside-pickle',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "cebu-city-a4-pickleball": {
    courtogo: 'https://www.courtogo.com/venues/a4-pickleball-',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "cebu-city-jpzr-private-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/alrajj-private-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "cebu-city-the-paddle-house": {
    courtogo: 'https://www.courtogo.com/venues/the-paddle-pod',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "chibs-n-dink": {
    courtogo: 'https://www.courtogo.com/venues/chibs-n-dink',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "cordova-the-paddle-co": {
    courtogo: 'https://www.courtogo.com/venues/the-paddle-pod',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "corner-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "courtside-cebu": {
    courtogo: 'https://www.courtogo.com/venues/the-courtside-pickle',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dink-district-ph": {
    courtogo: 'https://www.courtogo.com/venues/dink-district',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dink-n-lob": {
    courtogo: 'https://www.courtogo.com/venues/chibs-n-dink',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dink-spot-davao": {
    courtogo: 'https://www.courtogo.com/venues/d-dink-spot',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dink-xcape-picklehub": {
    courtogo: 'https://www.courtogo.com/venues/dink-xcape-picklehub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dinkers-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dinkwondo-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dinkz-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "dula-pickleball-courts": {
    courtogo: 'https://www.courtogo.com/venues/la-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "front-yard-pickle": {
    courtogo: 'https://www.courtogo.com/venues/pf-pickle-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "hacienda-pickleball-club": {
    courtogo: 'https://www.courtogo.com/venues/dcb-pickleball-club',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "hideaway-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "homecourt-yard": {
    courtogo: 'https://www.courtogo.com/venues/homecourt-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "hq-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "island-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "jb-pickleball": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "jpzr-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "kennydink-pickleball-court-moalboal": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "lapu-lapu-city-kenzo-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "lapu-lapu-city-mactan-pickleball-club": {
    courtogo: 'https://www.courtogo.com/venues/dcb-pickleball-club',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "lapu-lapu-city-pickle-pares-hub": {
    courtogo: 'https://www.courtogo.com/venues/redpoint-pickle-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "lapu-lapu-city-supreme-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "lapu-lapu-city-the-pickle-grounds": {
    courtogo: 'https://www.courtogo.com/venues/the-paddle-grounds',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "liloan-b-j-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "linkers-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "mergrande-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "minglanilla-picklehaus": {
    courtogo: 'https://www.courtogo.com/venues/picklehaus-',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "nine-ten": {
    courtogo: 'https://www.courtogo.com/venues/-910',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "north-point-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/north-point-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "orosia-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "paddiemates-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "paddle-ground": {
    courtogo: 'https://www.courtogo.com/venues/paddle-ground',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "paddle-ground-bacolod": {
    courtogo: 'https://www.courtogo.com/venues/paddle-ground',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "paddle-yard": {
    courtogo: 'https://www.courtogo.com/venues/paddle-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "paduwa-pickleball-club": {
    courtogo: 'https://www.courtogo.com/venues/dcb-pickleball-club',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "palm-pickleball-club": {
    courtogo: 'https://www.courtogo.com/venues/dcb-pickleball-club',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "pals-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "parqlinks-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "pick-and-paddle-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/frontyard-pickleball-and-typti-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "pickl-at-pilit": {
    courtogo: 'https://www.courtogo.com/venues/pickl-pilit',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "pickle-heart-court": {
    courtogo: 'https://www.courtogo.com/venues/jims-pickle-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "picklebear-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "pino-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "prime-pickle-point-midsayap": {
    courtogo: 'https://www.courtogo.com/venues/pickle-point',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "qusina-piqle-qlub": {
    sports360: 'https://app.sports360.ph/sportshub/qusina-piqle-qlub',
    platform: 'Sport360',
    label: 'Book via Sport360'
  },
  "reca-resort-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/lao-resort-pickleball-covered-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "sage-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "sam-s-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "sayson-s-place-private-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/alrajj-private-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "sip-and-serve": {
    courtogo: 'https://www.courtogo.com/venues/sip-serve',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "smash-sports-facilities": {
    sports360: 'https://app.sports360.ph/sportshub/smash',
    platform: 'Sport360',
    label: 'Book via Sport360'
  },
  "sogod-the-paddle-yard": {
    courtogo: 'https://www.courtogo.com/venues/the-paddle-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "sootk-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-courts-of-cebu": {
    onda: 'https://app.onda.fit/book/the-courts-of-cebu',
    platform: 'Onda Fit',
    label: 'Book via Onda Fit'
  },
  "the-dink-spot": {
    courtogo: 'https://www.courtogo.com/venues/d-dink-spot',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-mqz-court": {
    courtogo: 'https://www.courtogo.com/venues/the-backyard-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-paddle-hideout": {
    courtogo: 'https://www.courtogo.com/venues/the-paddle-pod',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-pickle-mill": {
    courtogo: 'https://www.courtogo.com/venues/the-courtside-pickle',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-pickle-park-mactan": {
    courtogo: 'https://www.courtogo.com/venues/pickle-park',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-pickle-pod": {
    courtogo: 'https://www.courtogo.com/venues/the-paddle-pod',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-pickle-point-cebu": {
    courtogo: 'https://www.courtogo.com/venues/pickle-point',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-pickle-yard-dasmari-as": {
    courtogo: 'https://www.courtogo.com/venues/pickle-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-pickle-yard-para-aque": {
    courtogo: 'https://www.courtogo.com/venues/pickle-yard',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-rally-point": {
    courtogo: 'https://www.courtogo.com/venues/the-smash-point',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "the-smash-city": {
    courtogo: 'https://www.courtogo.com/venues/the-smash-point',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "thirsty-pickle": {
    onda: 'https://app.onda.fit/book/thirsty-pickle',
    platform: 'Onda Fit',
    label: 'Book via Onda Fit'
  },
  "tierra-pickleball-club": {
    courtogo: 'https://www.courtogo.com/venues/dcb-pickleball-club',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "topspin-pickleball-court": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "velocity-pickleball-hub": {
    courtogo: 'https://www.courtogo.com/venues/rams-pickleball-hub',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "vista-court-pickleball": {
    courtogo: 'https://www.courtogo.com/venues/niceserve-pickleball-court',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "vybe-picklehaus": {
    courtogo: 'https://www.courtogo.com/venues/picklehaus-',
    platform: 'Courtogo',
    label: 'Book via Courtogo'
  },
  "arvo-pickleball": {
    website: 'https://arvopickleball.com',
    platform: 'Website',
    label: 'Visit Website'
  },
  "dink-shot": {
    website: 'https://dinkandshot.com',
    platform: 'Website',
    label: 'Visit Website'
  },
  "alset-pickleball": {
    website: 'https://alsetpickleball.ph/',
    platform: 'Website',
    label: 'Visit Website'
  },
  "baseline-pickle-hub-davao": {
    website: 'https://baseline.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "bacolod-pickleball-hq": {
    website: 'https://gmail.com',
    platform: 'Website',
    label: 'Visit Website'
  },
  "the-pickleball-hideout-bacolod": {
    website: 'https://the.pickleball.hi',
    platform: 'Website',
    label: 'Visit Website'
  },
  "netplay-360-iloilo": {
    website: 'https://netplay360.com',
    platform: 'Website',
    label: 'Visit Website'
  },
  "terra-courts": {
    website: 'https://terracourts.setmore.co',
    platform: 'Website',
    label: 'Visit Website'
  },
  "match-point-racket-club": {
    website: 'https://matchpointracketclub.com',
    platform: 'Website',
    label: 'Visit Website'
  },
  "mts-davao-pickleball": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "mts-davao-pickleball": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-space": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-space": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "azuela-play-courts": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "azuela-play-courts": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "court-88": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "court-88": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "da-hub-paddle-court": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "da-hub-paddle-court": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "davao-pickleyard": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "davao-pickleyard": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "dinklab": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "dinklab": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "matchpoint-pickleball": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "matchpoint-pickleball": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "the-pink-paddle-club": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "the-pink-paddle-club": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "the-premier-court-air-conditioned": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "the-premier-court-air-conditioned": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-world-limketkai": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-world-limketkai": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "third-shot-pickleground-gensan": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "third-shot-pickleground-gensan": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "dink-dunk-sports-center": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "dink-dunk-sports-center": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "city-pickle-grounds": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "city-pickle-grounds": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "paddle-point-tagum": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "paddle-point-tagum": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "picklezone-tagum": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "picklezone-tagum": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "m-central-pickleball-club": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "m-central-pickleball-club": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "big-j-paddlegrounds-mankilam": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "big-j-paddlegrounds-mankilam": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "paddle-hour": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "paddle-hour": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "play-77-sports-court": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "play-77-sports-court": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pmax": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pmax": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "cabin-pickle-club-gensan": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "cabin-pickle-club-gensan": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-world-gensan-downtown": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-world-gensan-downtown": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "court-zero-racquet-club": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "court-zero-racquet-club": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "kwiky-mart-pickle-bull": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "kwiky-mart-pickle-bull": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-barn-gsc": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-barn-gsc": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-panic-by-lagare-farms-parks": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-panic-by-lagare-farms-parks": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "v-park": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "v-park": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "o2-kidapawan": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "o2-kidapawan": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "primecourt-kidapawan": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "primecourt-kidapawan": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-farm-9400": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-farm-9400": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "panabo-paddle-house": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "panabo-paddle-house": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-power-nabunturan": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-power-nabunturan": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "antonio-s-highway-dinks": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "antonio-s-highway-dinks": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "courtside-brew": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "courtside-brew": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "dpicklezone": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "dpicklezone": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "elijah-s-pickle-place": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "elijah-s-pickle-place": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "mbh-pickleball-corner": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "mbh-pickleball-corner": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "monica-del-sol-resort": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "monica-del-sol-resort": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "paraiso-verde-picklehall": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "paraiso-verde-picklehall": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-at-the-barn": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-at-the-barn": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickleboy-kabacan": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickleboy-kabacan": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "primo-pickleball": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "primo-pickleball": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "smashwin-pickleball-courts": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "smashwin-pickleball-courts": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "fpb-sports-complex": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "fpb-sports-complex": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pick-a-boo-pickleball-davao": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pick-a-boo-pickleball-davao": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-blue": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-blue": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-ground": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-ground": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickleball-kitchen-monsta-davao": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickleball-kitchen-monsta-davao": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "the-forge": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "the-forge": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "tierra-sports-hub": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "tierra-sports-hub": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "paddle-rush": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "paddle-rush": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "picklerange": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "picklerange": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "metro-pickle-club": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "metro-pickle-club": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "sideout-pickleball-courts": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "sideout-pickleball-courts": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "929-pickleyard": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "929-pickleyard": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "ace-pickleyard-sports-center": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "ace-pickleyard-sports-center": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "after-five-pickle-hub": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "after-five-pickle-hub": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "dink-n-dine-south": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "dink-n-dine-south": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "dinkstiny-sport-center": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "dinkstiny-sport-center": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "elle-square-lily-s-pickle-club": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "elle-square-lily-s-pickle-club": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "flying-pickle-sports-center": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "flying-pickle-sports-center": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "hacienda-grande-assoc-pickle-court": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "hacienda-grande-assoc-pickle-court": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "hapak-court-by-pantukan-water-world": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "hapak-court-by-pantukan-water-world": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "jorge-pickle-town": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "jorge-pickle-town": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "malvar-dinkerz": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "malvar-dinkerz": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "mimic-courtyard": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "mimic-courtyard": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "neon-paddle-club": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "neon-paddle-club": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "norberto-s-pickle-kitchen": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "norberto-s-pickle-kitchen": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "paddlepals-recreational-hub": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "paddlepals-recreational-hub": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "padel-more-davao": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "padel-more-davao": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "padel-smash-grounds": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "padel-smash-grounds": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-bliss": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-bliss": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-pals": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-pals": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-pirates": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-pirates": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickle-spot-samal": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickle-spot-samal": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickleball-hideout": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickleball-hideout": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickleholics": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickleholics": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "pickleyam-kabacan": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "pickleyam-kabacan": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "slide-two-pickleball": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "slide-two-pickleball": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "sosyal-dinkers-pickleball-court": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "sosyal-dinkers-pickleball-court": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
  "the-pinkle-zone": {
    picklehub: 'https://PickleHub.ph',
    platform: 'PickleHub',
    label: 'Listed on PickleHub'
  },
  "the-pinkle-zone": {
    website: 'https://PickleHub.ph',
    platform: 'Website',
    label: 'Visit Website'
  },
};

// ============================================================
// Lookup function
// ============================================================
function getBookingInfo(courtId, courtName) {
  const key = courtId || (courtName ? courtName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') : '');
  return BOOKING_BY_ID[key] || null;
}

// ============================================================
// Helper: generate "Book Now" button HTML
// ============================================================
function getBookingButtonHtml(courtId, courtName) {
  const info = getBookingInfo(courtId, courtName);
  if (!info) return '';
  
  const url = info.courtogo || info.onda || info.sports360 || info.playserve || info.picklehub || info.website || info.facebook;
  if (!url) return '';
  
  const colorMap = {
    'Onda Fit': '#6366f1',
    'Courtogo': '#0891b2',
    'Sport360': '#059669',
    'PlayServe': '#7c3aed',
    'PickleHub': '#ea580c',
    'Website': '#2563eb',
    'Facebook': '#1877f2'
  };
  const color = colorMap[info.platform] || '#2563eb';
  
  return '<a href="'+url+'" target="_blank" rel="noopener" class="btn-submit" style="display:block;text-align:center;background:'+color+';margin-top:8px"><i class="fas fa-external-link-alt"></i> '+info.label+'</a>';
}

// Make available globally
if (typeof window !== 'undefined') {
  window.BOOKING_BY_ID = BOOKING_BY_ID;
  window.getBookingInfo = getBookingInfo;
  window.getBookingButtonHtml = getBookingButtonHtml;
}